# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import numpy
import numpy.typing
import typing
__all__ = [
    "Capabilities",
    "Device",
    "DeviceBusy",
    "DeviceNotFound",
    "Discovery",
    "MediaError",
    "ScanCancelled",
    "ScanResult",
    "ScannerError",
    "Session",
    "TransientError",
    "TransportError",
    "UnsupportedError",
    "list_devices",
]

@typing.final
class Capabilities:
    r"""
    What the scanner says it can do, projected down to what a caller needs to
    place a scan. Grows as bindings turn up a real need for more of it
    """
    @property
    def vendor(self) -> builtins.str: ...
    @property
    def product(self) -> builtins.str: ...
    @property
    def revision(self) -> builtins.str: ...
    @property
    def model(self) -> typing.Optional[builtins.str]: ...
    @property
    def x_dpi_range(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def y_dpi_range(self) -> tuple[builtins.int, builtins.int]: ...
    @property
    def optical_dpi(self) -> builtins.int: ...
    @property
    def multiline_read(self) -> builtins.bool:
        r"""
        Whether the unit reads the CCD three rows at once, the faster of the two
        reads. Where it does not, every scan is one row at a time and
        `scan_frame`'s `superfine` is the only thing it will do
        """
    @property
    def multi_reading(self) -> builtins.bool:
        r"""
        Whether the unit honours repeated reads of a line, so `scan_frame`'s
        `samples` above 1 means anything
        """

@typing.final
class Device:
    r"""
    A scanner this library found, and can open
    """
    @property
    def location(self) -> builtins.str:
        r"""
        Where it is
        """
    @property
    def name(self) -> builtins.str:
        r"""
        What to show a person
        """
    def __repr__(self) -> builtins.str: ...

class DeviceBusy(TransientError):
    r"""
    Something else has the scanner
    """
    ...

class DeviceNotFound(ScannerError):
    r"""
    No such scanner
    """
    ...

@typing.final
class Discovery:
    r"""
    What discovery found
    """
    @property
    def frames(self) -> builtins.list[tuple[builtins.int, builtins.int, builtins.int, builtins.int]]: ...
    @property
    def thumbnail(self) -> typing.Optional[builtins.dict[builtins.str, numpy.typing.NDArray[numpy.uint16]]]:
        r"""
        One array per channel, keyed the way `ScanResult.colors` is;
        `None` where the mechanism that found `frames` needed no thumbnail pass
        """

class MediaError(ScannerError):
    r"""
    Something a person has to go fix
    """
    ...

class ScanCancelled(ScannerError):
    r"""
    A progress callback returned False
    """
    ...

@typing.final
class ScanResult:
    r"""
    What one frame's scan produced
    """
    @property
    def colors(self) -> builtins.dict[builtins.str, numpy.typing.NDArray[numpy.uint16]]:
        r"""
        One array per captured channel, keyed by name ("red", "green", "blue", ...)
        """
    @property
    def ir(self) -> typing.Optional[numpy.typing.NDArray[numpy.uint16]]:
        r"""
        The infrared plane, where the recipe asked for it
        """
    @property
    def dpi(self) -> builtins.int: ...
    @property
    def rows(self) -> builtins.int: ...
    @property
    def cols(self) -> builtins.int: ...
    @property
    def exposures(self) -> builtins.dict[builtins.str, builtins.int]:
        r"""
        What the frame was exposed at, keyed the same way as `colors`
        """
    @property
    def cleaned(self) -> typing.Optional[builtins.int]:
        r"""
        Pixels dust removal rebuilt, where asked for
        """

class ScannerError(builtins.RuntimeError):
    r"""
    Base for every error this crate raises
    """
    ...

@typing.final
class Session:
    r"""
    An open, exclusive hold of a scanner
    """
    @property
    def capabilities(self) -> Capabilities:
        r"""
        What the scanner says it can do
        """
    def __new__(cls, location: builtins.str) -> Session:
        r"""
        Start a session against whatever `list_devices` reports at this `location`
        """
    @staticmethod
    def open(device: Device) -> Session:
        r"""
        Start a session against `device`
        """
    def media_loaded(self) -> builtins.bool:
        r"""
        Whether a holder is loaded
        """
    def stage(self) -> None:
        r"""
        Put the unit in the state a scan expects
        """
    def eject(self) -> builtins.bool:
        r"""
        Give back whatever is loaded, answering whether the unit did anything
        """
    def load(self) -> builtins.bool:
        r"""
        Take in whatever the adapter has waiting, answering whether anything came
        """
    def discover_frames(self, format: typing.Optional[builtins.str] = None, positive: builtins.bool = False, progress: typing.Optional[typing.Any] = None) -> Discovery:
        r"""
        Find every frame on whatever is loaded
        
        `format` is one of "135", "half", "IX240", "16", "645", "66", "67",
        "68", "69", or a custom frame length in mm as a string (e.g. "56").
        Only asked for by the two of four discovery mechanisms that need a
        thumbnail pass to find frames, and even there only where the loaded
        holder does not fix or narrow it by itself, so it can usually be left
        `None`. `positive` is which way the loaded film reads.
        `Discovery.thumbnail`, where the mechanism took one, is what a caller
        wanting to nudge `Discovery.frames` by hand shows the operator: a
        rectangle handed to `scan_frame` needs no match in it, so a nudged one
        works the same as a detected one, just slower if the stage has to home
        first to reach it
        """
    def scan_frame(self, frame: tuple[builtins.int, builtins.int, builtins.int, builtins.int], dpi: typing.Optional[builtins.int] = None, samples: builtins.int = 1, superfine: builtins.bool = False, infrared: builtins.bool = False, clean: builtins.bool = False, lock_white_balance: builtins.bool = True, exposures: typing.Optional[typing.Mapping[builtins.str, builtins.int]] = None, progress: typing.Optional[typing.Any] = None) -> ScanResult:
        r"""
        Focus, meter, take the pass over `frame`, and optionally clean it
        
        `frame` is `(top, left, bottom, right)`, one of `discover_frames`'s. `exposures`,
        keyed the way `ScanResult.exposures` is, reuses an exposure already decided
        rather than metering this frame fresh
        """
    def close(self) -> None:
        r"""
        Drop the hold on the scanner. A closed session refuses every other method
        """
    def __enter__(self) -> Session: ...
    def __exit__(self, *_args: typing.Any) -> None: ...

class TransientError(ScannerError):
    r"""
    Worth retrying
    """
    ...

class TransportError(TransientError):
    r"""
    The link to the scanner failed
    """
    ...

class UnsupportedError(ScannerError):
    r"""
    This unit or adapter cannot do that. Carries `.op` and `.reason`
    """
    ...

def list_devices() -> builtins.list[Device]:
    r"""
    Every scanner this library thinks it can drive
    """

